(() => {
  const species=[
    {name:'Snow leopard',latin:'Panthera uncia',clue:'A solitary mountain cat built for high, cold terrain.',habitat:'High alpine',hint:'Look across the great mountain systems of Central Asia.',countries:['AF','BT','CN','IN','KZ','KG','MN','NP','PK','RU','TJ','UZ'],anchor:{lat:35.7,lon:75.8}},
    {name:'Galápagos tortoise',latin:'Chelonoidis niger',clue:'A giant island reptile with a life measured in centuries.',habitat:'Volcanic islands',hint:'Think of a small Pacific archipelago west of Ecuador.',countries:['EC'],geometry:'POLYGON((-91.8 -1.8,-89.7 -1.8,-89.7 0.4,-91.8 0.4,-91.8 -1.8))',anchor:{lat:-.7,lon:-90.4}},
    {name:'Red kangaroo',latin:'Osphranter rufus',clue:'A powerful hopper adapted to dry, open landscapes.',habitat:'Arid grassland',hint:'It is widespread through Australia’s interior.',countries:['AU'],anchor:{lat:-25.3,lon:133.8}},
    {name:'Emperor penguin',latin:'Aptenodytes forsteri',clue:'This bird incubates its egg through the darkest polar winter.',habitat:'Sea ice',hint:'Its colonies ring the southernmost continent.',countries:['AQ'],anchor:{lat:-76.4,lon:161}},
    {name:'Okapi',latin:'Okapia johnstoni',clue:'A forest-dwelling relative of the giraffe, striped at the hind legs.',habitat:'Dense rainforest',hint:'Look to the Congo Basin in central Africa.',countries:['CD'],anchor:{lat:.8,lon:25.2}},
    {name:'Axolotl',latin:'Ambystoma mexicanum',clue:'A permanently aquatic salamander native to a high-altitude lake system.',habitat:'Freshwater wetland',hint:'Its only native home is in the basin of Mexico City.',countries:['MX'],geometry:'POLYGON((-99.28 19.12,-98.98 19.12,-98.98 19.48,-99.28 19.48,-99.28 19.12))',anchor:{lat:19.3,lon:-99.1}},
    {name:'Komodo dragon',latin:'Varanus komodoensis',clue:'The largest living lizard survives on a handful of hot islands.',habitat:'Seasonal islands',hint:'Find the Lesser Sunda Islands of Indonesia.',countries:['ID'],geometry:'POLYGON((118.5 -9.5,122.7 -9.5,122.7 -7.5,118.5 -7.5,118.5 -9.5))',anchor:{lat:-8.6,lon:119.5}},
    {name:'American bison',latin:'Bison bison',clue:'A herd animal of broad temperate grasslands.',habitat:'Prairie',hint:'Its historic range spans the central plains of North America.',countries:['US','CA'],geometry:'POLYGON((-116 39,-88 39,-88 57,-116 57,-116 39))',anchor:{lat:46.5,lon:-101.5}}
  ];
  const $=id=>document.getElementById(id),empty=()=>({type:'FeatureCollection',features:[]}),point=(lon,lat)=>({type:'Feature',properties:{},geometry:{type:'Point',coordinates:[lon,lat]}});
  const map=new maplibregl.Map({container:'world-map',style:'https://tiles.openfreemap.org/styles/liberty',center:[8,16],zoom:2,minZoom:1.4,maxZoom:18,renderWorldCopies:true,attributionControl:true});
  map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');
  const gbifCache=new Map();let index=0,score=0,streak=0,selected=null,answered=false,revealed=false;
  const distanceKm=(a,b)=>{const r=d=>d*Math.PI/180,dLat=r(b.lat-a.lat),dLon=r(b.lon-a.lon),v=Math.sin(dLat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v));};
  const setData=(name,data)=>map.getSource(name)?.setData(data);
  function updateStats(){$('score').textContent=score.toLocaleString();$('streak').textContent=streak;}
  function clearResult(){setData('guess',empty());setData('observations',empty());setData('target',empty());setData('result-line',empty());$('round-result').classList.remove('visible');$('round-result').textContent='';}
  function renderRound(){const s=species[index];selected=null;answered=false;revealed=false;clearResult();$('species-name').textContent=s.name;$('latin-name').textContent=s.latin;$('species-clue').textContent=s.clue;$('habitat-tag').textContent=s.habitat;$('record-id').textContent=('0'+(index+1)).slice(-2)+' / '+('0'+species.length).slice(-2);$('round-count').textContent=(index+1)+' / '+species.length;$('map-heading').textContent='Drag, zoom, then click to place your marker';$('map-state').textContent='Awaiting pin';$('map-note').innerHTML='Drag to pan, zoom in for island habitats, then click to place your marker.';$('hint-btn').disabled=false;$('hint-btn').textContent='Use habitat hint';$('submit-btn').hidden=false;$('next-btn').hidden=true;map.jumpTo({center:[8,16],zoom:2});}
  function renderObservations(records){setData('observations',{type:'FeatureCollection',features:records.map(r=>point(r.lon,r.lat))});}
  async function getGbifRecords(s){if(gbifCache.has(s.latin))return gbifCache.get(s.latin);const match=await (await fetch('https://api.gbif.org/v1/species/match?name='+encodeURIComponent(s.latin))).json();if(!match.usageKey)throw Error('Species not found');const q=new URLSearchParams({taxon_key:match.usageKey,has_coordinate:'true',has_geospatial_issue:'false',limit:'300'});s.countries.forEach(c=>q.append('country',c));q.append('basis_of_record','HUMAN_OBSERVATION');q.append('basis_of_record','PRESERVED_SPECIMEN');if(s.geometry)q.set('geometry',s.geometry);const response=await fetch('https://api.gbif.org/v1/occurrence/search?'+q);if(!response.ok)throw Error('Observation request failed');const records=(await response.json()).results.filter(r=>Number.isFinite(r.decimalLatitude)&&Number.isFinite(r.decimalLongitude)).map(r=>({lat:r.decimalLatitude,lon:r.decimalLongitude}));if(!records.length)throw Error('No observations');gbifCache.set(s.latin,records);return records;}
  function animateResult(target,km,gained){const start=[selected.lon,selected.lat],end=[target.lon,target.lat];setData('target',{type:'FeatureCollection',features:[point(...end)]});const started=performance.now(),duration=900;const draw=now=>{const p=Math.min(1,(now-started)/duration),e=1-(1-p)**3,at=[start[0]+(end[0]-start[0])*e,start[1]+(end[1]-start[1])*e];setData('result-line',{type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[start,at]}}]});if(p<1){requestAnimationFrame(draw);return;}$('round-result').innerHTML='<strong>+'+gained.toLocaleString()+' points</strong> &nbsp;·&nbsp; '+km.toLocaleString()+' km away';$('round-result').classList.add('visible');};requestAnimationFrame(draw);}
  function revealAndAnimate(target,km,gained){const targetLngLat=[target.lon,target.lat],guessLngLat=[selected.lon,selected.lat];map.jumpTo({center:targetLngLat});setTimeout(()=>{const b=new maplibregl.LngLatBounds(targetLngLat,targetLngLat).extend(guessLngLat);map.fitBounds(b,{padding:80,maxZoom:4,duration:0});setTimeout(()=>animateResult(target,km,gained),120);},300);}
  map.on('click',event=>{if(answered)return;selected={lat:event.lngLat.lat,lon:event.lngLat.lng};setData('guess',{type:'FeatureCollection',features:[point(selected.lon,selected.lat)]});$('map-heading').textContent='Marker placed — lock in when ready';$('map-state').textContent='Pin ready';});
  $('hint-btn').addEventListener('click',()=>{if(answered)return;revealed=true;$('hint-btn').disabled=true;$('hint-btn').textContent='Hint used';$('map-note').innerHTML='<strong>Habitat hint:</strong> '+species[index].hint;});
  async function finishRound(){const s=species[index];if(!selected){$('map-note').innerHTML='<strong>Place a marker first.</strong> Your best guess counts.';return;}answered=true;$('submit-btn').hidden=true;$('hint-btn').disabled=true;$('map-heading').textContent='Loading filtered observations';$('map-state').textContent='GBIF lookup';try{const records=await getGbifRecords(s),nearest=records.reduce((best,r)=>distanceKm(selected,r)<distanceKm(selected,best)?r:best,records[0]),km=Math.round(distanceKm(selected,nearest)),gained=Math.round(5000*Math.exp(-km/1200)*(revealed ? .82 : 1));score+=gained;streak=gained>=2500?streak+1:0;updateStats();renderObservations(records);$('map-heading').textContent=km===0?'On a documented observation':km.toLocaleString()+' km from the nearest documented observation';$('map-state').textContent='+'+gained.toLocaleString()+' points';$('map-note').innerHTML='<strong>'+records.length+' region-filtered GBIF observations</strong> are shown in coral.';revealAndAnimate(nearest,km,gained);}catch(error){const km=Math.round(distanceKm(selected,s.anchor)),gained=Math.round(2500*Math.exp(-km/2600));score+=gained;updateStats();$('map-heading').textContent='Observation lookup unavailable';$('map-state').textContent='+'+gained.toLocaleString()+' points';$('map-note').innerHTML='Filtered GBIF observations could not be loaded. Your score used the species reference location instead.';revealAndAnimate(s.anchor,km,gained);}finally{$('next-btn').hidden=false;}}
  $('submit-btn').addEventListener('click',finishRound);$('next-btn').addEventListener('click',()=>{index++;if(index>=species.length){$('final-score').textContent=score.toLocaleString()+' points';$('end-card').classList.add('visible');}else renderRound();});$('restart-btn').addEventListener('click',()=>{index=0;score=0;streak=0;updateStats();$('end-card').classList.remove('visible');renderRound();});
  map.on('load',()=>{[['observations','#ff806b',4],['guess','#ffcc66',8],['target','#ff806b',9]].forEach(([name,color,radius])=>{map.addSource(name,{type:'geojson',data:empty()});map.addLayer({id:name,type:'circle',source:name,paint:{'circle-radius':radius,'circle-color':color,'circle-stroke-width':2,'circle-stroke-color':'#fff5d9'}});});map.addSource('result-line',{type:'geojson',data:empty()});map.addLayer({id:'result-line',type:'line',source:'result-line',paint:{'line-color':'#ffcc66','line-width':4,'line-opacity':.95}});updateStats();renderRound();});
  new ResizeObserver(()=>map.resize()).observe($('world-map'));
})();
